{
 "title": "OpenTelemetry Service Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Duration (p95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket[1m])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_count[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{http_status=~\"5..\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "External HTTP Latency (p95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_duration_bucket[1m])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "External HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(http_client_duration_count[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_runtime_dotnet_gc_pause_time_sum[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_memory_rss", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "rate(process_cpu_time[1m])", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "service_uptime_seconds", "legendFormat": "{{le}}" }
   ]
  }
 ]
}